import {
  BOOTSTRAP_CATEGORIES,
  BOOTSTRAP_READINESS_CONTRACT_VERSION,
  BootstrapReadinessContractSchema,
  BootstrapReadinessSummarySchema,
  BootstrapRequirementSchema,
  BootstrapValidationTargetSchema,
  type BootstrapCategory,
  type BootstrapReadinessContract,
  type BootstrapReadinessSummary,
  type BootstrapRequirement,
  type BootstrapRequirementKind,
  type BootstrapValidationTarget,
} from "./contracts";

const REQUIREMENTS = [
  {
    requirement_id: "bootstrap-req:node",
    label: "Node.js runtime",
    category: "environment",
    kind: "required",
    must_exist:
      "Node.js 20 or newer must be available for Next.js, TypeScript, tests, and local scripts.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:node-version"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:npm-pnpm",
    label: "npm and pnpm package managers",
    category: "environment",
    kind: "required",
    must_exist:
      "npm is available with Node.js and pnpm 9 or newer is expected for bootstrap parity with operationalization docs.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:package-manager"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:typescript",
    label: "TypeScript toolchain",
    category: "environment",
    kind: "required",
    must_exist:
      "TypeScript must be present through project dependencies so `npx tsc --noEmit` can verify strict contracts.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:typescript-available"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:platform-support",
    label: "Supported local platform",
    category: "environment",
    kind: "required",
    must_exist:
      "macOS and Linux are supported local-first bootstrap targets; Windows remains unsupported by the existing Phase 10 contract.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:platform-family"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:ollama",
    label: "Ollama local service",
    category: "runtime",
    kind: "local_first",
    must_exist:
      "Ollama is the planned local model runtime for Phase 13 model execution, but this contract does not start or inspect it.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:ollama-local-runtime"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:local-model-runtime",
    label: "Local model registry/runtime",
    category: "runtime",
    kind: "local_first",
    must_exist:
      "Local model registry files and runtime contracts must exist; cloud fallback remains disabled unless explicitly governed.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: true,
    validation_target_ids: [
      "bootstrap-validation:ollama-local-runtime",
      "bootstrap-validation:registry-files",
    ],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:sqlite",
    label: "SQLite persistence package",
    category: "runtime",
    kind: "required",
    must_exist:
      "better-sqlite3 and migration/schema modules must be available for the local persistence substrate.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:sqlite-package"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:tauri",
    label: "Tauri desktop shell prerequisites",
    category: "runtime",
    kind: "required",
    must_exist:
      "Tauri CLI, Rust toolchain, and src-tauri configuration are required for later packaging hardening.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:tauri-toolchain"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:voice-runtime-prerequisites",
    label: "Voice runtime prerequisites",
    category: "runtime",
    kind: "optional",
    must_exist:
      "Local STT/TTS prerequisites are needed for voice realization, while wake word, always-listening, and cloud voice remain disabled.",
    optional_reason:
      "Voice is not required to prove baseline bootstrap readiness, but must be documented for move-in readiness.",
    disabled_by_default: true,
    local_first: true,
    cloud_gated: true,
    validation_target_ids: ["bootstrap-validation:voice-local-prerequisites"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:vision-runtime-prerequisites",
    label: "Vision runtime prerequisites",
    category: "runtime",
    kind: "optional",
    must_exist:
      "Local OCR/object-detection prerequisites are needed for vision realization, while background camera and cloud vision remain disabled.",
    optional_reason:
      "Vision is not required to prove baseline bootstrap readiness, but must be documented for move-in readiness.",
    disabled_by_default: true,
    local_first: true,
    cloud_gated: true,
    validation_target_ids: ["bootstrap-validation:vision-local-prerequisites"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:required-directories",
    label: "Required project directories",
    category: "project",
    kind: "required",
    must_exist:
      "app, src, config, db, docs, scripts, tests, src-tauri, models, and workspace directories form the expected local project layout.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:project-layout"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:required-config-files",
    label: "Required config files",
    category: "project",
    kind: "required",
    must_exist:
      "package.json, tsconfig.json, next.config.ts, vitest.config.ts, config/room/default-room.yaml, and config/models/registry.yaml must be present.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: ["bootstrap-validation:config-files"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:required-env-files",
    label: "Required environment defaults",
    category: "project",
    kind: "disabled_by_default",
    must_exist:
      ".env.local or future .env.example values must preserve local-only, remote-dashboard-disabled, and real-provider-disabled defaults.",
    optional_reason: null,
    disabled_by_default: true,
    local_first: true,
    cloud_gated: true,
    validation_target_ids: ["bootstrap-validation:env-safe-defaults"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:required-registries",
    label: "Required registries",
    category: "project",
    kind: "required",
    must_exist:
      "Model, room, tool, project, routine, architecture, disabled-feature, and authority registries must remain present and deterministic.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: true,
    validation_target_ids: ["bootstrap-validation:registry-files"],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:readiness-checks",
    label: "Readiness checks",
    category: "validation",
    kind: "required",
    must_exist:
      "Targeted and full validation expectations must be declared for tests, TypeScript, lint, doctor, and future packaging checks.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: [
      "bootstrap-validation:doctor-readiness",
      "bootstrap-validation:test-suite",
    ],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:doctor-integration-targets",
    label: "Doctor integration targets",
    category: "validation",
    kind: "required",
    must_exist:
      "Doctor integration targets must cover environment, package manager, resources, env defaults, provider defaults, and declared local ports.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: [
      "bootstrap-validation:doctor-readiness",
      "bootstrap-validation:node-version",
      "bootstrap-validation:package-manager",
      "bootstrap-validation:env-safe-defaults",
    ],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
  {
    requirement_id: "bootstrap-req:verification-expectations",
    label: "Verification expectations",
    category: "validation",
    kind: "required",
    must_exist:
      "Bootstrap readiness verification expects deterministic test, typecheck, lint, doctor, and future packaging-readiness results.",
    optional_reason: null,
    disabled_by_default: false,
    local_first: true,
    cloud_gated: false,
    validation_target_ids: [
      "bootstrap-validation:test-suite",
      "bootstrap-validation:doctor-readiness",
      "bootstrap-validation:tauri-toolchain",
    ],
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  },
] satisfies readonly BootstrapRequirement[];

const VALIDATION_TARGETS = [
  {
    target_id: "bootstrap-validation:node-version",
    label: "Node version expectation",
    category: "environment",
    validates_requirement_ids: ["bootstrap-req:node"],
    doctor_integration_target: true,
    verification_expectation:
      "Doctor should report supported Node major version without installing Node.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:package-manager",
    label: "Package manager expectation",
    category: "environment",
    validates_requirement_ids: ["bootstrap-req:npm-pnpm"],
    doctor_integration_target: true,
    verification_expectation:
      "Doctor should report pnpm availability without installing dependencies.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:typescript-available",
    label: "TypeScript expectation",
    category: "environment",
    validates_requirement_ids: ["bootstrap-req:typescript"],
    doctor_integration_target: false,
    verification_expectation:
      "TypeScript availability is verified by project validation, not by this contract.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:platform-family",
    label: "Platform support expectation",
    category: "environment",
    validates_requirement_ids: ["bootstrap-req:platform-support"],
    doctor_integration_target: true,
    verification_expectation:
      "Doctor should classify macOS and Linux as supported local targets and reject unsupported OS families.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:ollama-local-runtime",
    label: "Ollama local runtime expectation",
    category: "runtime",
    validates_requirement_ids: [
      "bootstrap-req:ollama",
      "bootstrap-req:local-model-runtime",
    ],
    doctor_integration_target: true,
    verification_expectation:
      "Future doctor hardening may report Ollama readiness without starting services or pulling models.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:sqlite-package",
    label: "SQLite package expectation",
    category: "runtime",
    validates_requirement_ids: ["bootstrap-req:sqlite"],
    doctor_integration_target: false,
    verification_expectation:
      "Persistence readiness is verified by local dependency and store tests, not runtime mutation here.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:tauri-toolchain",
    label: "Tauri toolchain expectation",
    category: "runtime",
    validates_requirement_ids: [
      "bootstrap-req:tauri",
      "bootstrap-req:verification-expectations",
    ],
    doctor_integration_target: true,
    verification_expectation:
      "Future doctor hardening may report Rust/Tauri readiness without building packages.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:voice-local-prerequisites",
    label: "Voice local prerequisite expectation",
    category: "runtime",
    validates_requirement_ids: ["bootstrap-req:voice-runtime-prerequisites"],
    doctor_integration_target: true,
    verification_expectation:
      "Future doctor hardening may report local STT/TTS readiness while cloud voice remains gated.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:vision-local-prerequisites",
    label: "Vision local prerequisite expectation",
    category: "runtime",
    validates_requirement_ids: ["bootstrap-req:vision-runtime-prerequisites"],
    doctor_integration_target: true,
    verification_expectation:
      "Future doctor hardening may report OCR/detection readiness while background camera and cloud vision remain gated.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:project-layout",
    label: "Project layout expectation",
    category: "project",
    validates_requirement_ids: ["bootstrap-req:required-directories"],
    doctor_integration_target: false,
    verification_expectation:
      "Project layout readiness is a declared expectation for future checks; this contract does not read the filesystem.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:config-files",
    label: "Config file expectation",
    category: "project",
    validates_requirement_ids: ["bootstrap-req:required-config-files"],
    doctor_integration_target: false,
    verification_expectation:
      "Config readiness is a declared expectation for future checks; this contract does not read config files.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:env-safe-defaults",
    label: "Safe environment defaults expectation",
    category: "project",
    validates_requirement_ids: ["bootstrap-req:required-env-files"],
    doctor_integration_target: true,
    verification_expectation:
      "Doctor should keep local-only and real-provider-disabled defaults visible without exposing secret values.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:registry-files",
    label: "Registry file expectation",
    category: "project",
    validates_requirement_ids: [
      "bootstrap-req:local-model-runtime",
      "bootstrap-req:required-registries",
    ],
    doctor_integration_target: false,
    verification_expectation:
      "Registry readiness is a declared expectation for future checks; this contract does not load registries.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:doctor-readiness",
    label: "Doctor readiness expectation",
    category: "validation",
    validates_requirement_ids: [
      "bootstrap-req:readiness-checks",
      "bootstrap-req:doctor-integration-targets",
      "bootstrap-req:verification-expectations",
    ],
    doctor_integration_target: true,
    verification_expectation:
      "Doctor should remain read-only and descriptive while reporting bootstrap readiness.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
  {
    target_id: "bootstrap-validation:test-suite",
    label: "Validation suite expectation",
    category: "validation",
    validates_requirement_ids: [
      "bootstrap-req:readiness-checks",
      "bootstrap-req:verification-expectations",
    ],
    doctor_integration_target: false,
    verification_expectation:
      "Readiness verification expects tests, typecheck, lint, and diff hygiene to pass when invoked by humans or CI.",
    metadata_only: true,
    read_only: true,
    deterministic: true,
    executes_check: false,
    shell_command_included: false,
    installs_dependency: false,
    mutates_environment: false,
    mutates_filesystem: false,
    calls_network: false,
    contacts_provider: false,
  },
] satisfies readonly BootstrapValidationTarget[];

function deepFreeze<T>(value: T): T {
  if (value && typeof value === "object") {
    for (const child of Object.values(value)) {
      deepFreeze(child);
    }

    return Object.freeze(value);
  }

  return value;
}

function copyContract(
  contract: BootstrapReadinessContract,
): BootstrapReadinessContract {
  return BootstrapReadinessContractSchema.parse(
    JSON.parse(JSON.stringify(contract)),
  );
}

function copyRequirement(
  requirement: BootstrapRequirement,
): BootstrapRequirement {
  return BootstrapRequirementSchema.parse(
    JSON.parse(JSON.stringify(requirement)),
  );
}

function copyTarget(
  target: BootstrapValidationTarget,
): BootstrapValidationTarget {
  return BootstrapValidationTargetSchema.parse(
    JSON.parse(JSON.stringify(target)),
  );
}

export const BOOTSTRAP_READINESS_CONTRACT = deepFreeze(
  BootstrapReadinessContractSchema.parse({
    contract_version: BOOTSTRAP_READINESS_CONTRACT_VERSION,
    contract_id: "phase-20b1-bootstrap-readiness-contract",
    phase: "20B.1",
    summary:
      "Metadata-only bootstrap readiness contract for fresh-machine JARVIS OS v1 prerequisites; it declares what must exist without installing, probing, or mutating anything.",
    categories: [...BOOTSTRAP_CATEGORIES],
    requirements: REQUIREMENTS,
    validation_targets: VALIDATION_TARGETS,
    posture: {
      contract_layer_only: true,
      metadata_only: true,
      read_only: true,
      deterministic: true,
      performs_installation: false,
      executes_shell: false,
      mutates_environment: false,
      mutates_filesystem: false,
      calls_network: false,
      contacts_provider: false,
      adds_runtime_hook: false,
      adds_bootstrap_automation: false,
      creates_authority_surface: false,
      creates_capability: false,
    },
  }),
);

export function getBootstrapReadinessContract(): BootstrapReadinessContract {
  return copyContract(BOOTSTRAP_READINESS_CONTRACT);
}

export function getBootstrapRequirements(): readonly BootstrapRequirement[] {
  return BOOTSTRAP_READINESS_CONTRACT.requirements.map(copyRequirement);
}

export function getBootstrapValidationTargets(): readonly BootstrapValidationTarget[] {
  return BOOTSTRAP_READINESS_CONTRACT.validation_targets.map(copyTarget);
}

export function summarizeBootstrapReadiness(): BootstrapReadinessSummary {
  const requirements = BOOTSTRAP_READINESS_CONTRACT.requirements;
  const targets = BOOTSTRAP_READINESS_CONTRACT.validation_targets;
  const categoryCounts = Object.fromEntries(
    BOOTSTRAP_CATEGORIES.map((category) => [
      category,
      requirements.filter((requirement) => requirement.category === category)
        .length,
    ]),
  ) as Record<BootstrapCategory, number>;
  const countKind = (kind: BootstrapRequirementKind) =>
    requirements.filter((requirement) => requirement.kind === kind).length;

  return BootstrapReadinessSummarySchema.parse({
    contract_version: BOOTSTRAP_READINESS_CONTRACT_VERSION,
    requirement_count: requirements.length,
    validation_target_count: targets.length,
    category_counts: categoryCounts,
    required_count: countKind("required"),
    optional_count: countKind("optional"),
    disabled_by_default_count: requirements.filter(
      (requirement) => requirement.disabled_by_default,
    ).length,
    local_first_count: requirements.filter(
      (requirement) => requirement.local_first,
    ).length,
    cloud_gated_count: requirements.filter(
      (requirement) => requirement.cloud_gated,
    ).length,
    doctor_integration_target_count: targets.filter(
      (target) => target.doctor_integration_target,
    ).length,
    metadata_only: true,
    read_only: true,
    deterministic: true,
    installation_executed: false,
    shell_invocation_enabled: false,
    filesystem_mutation_enabled: false,
    network_call_enabled: false,
    provider_call_enabled: false,
    runtime_hook_enabled: false,
    authority_surface_created: false,
    capability_created: false,
  });
}
