export {
  buildObsidianVaultIndex,
  getObsidianNoteMetadata,
  getObsidianNoteSnippet,
  loadObsidianVaultConfig,
  OBSIDIAN_INDEX_MAX_NOTE_BYTES,
  OBSIDIAN_SNIPPET_DEFAULT_CHARS,
  OBSIDIAN_SNIPPET_MAX_CHARS,
  OBSIDIAN_VAULT_PATH_ENV,
  ObsidianVaultPathError,
  validateObsidianVaultPath,
  type BuildObsidianVaultIndexOptions,
  type ObsidianFolderMetadata,
  type ObsidianLookupInput,
  type ObsidianNoteMetadata,
  type ObsidianSnippet,
  type ObsidianSnippetInput,
  type ObsidianVaultConfig,
  type ObsidianVaultIndex,
  type ObsidianVaultPathErrorReason,
} from "./pull-indexer";

export {
  countObsidianVectors,
  createObsidianLocalEmbeddingProvider,
  initializeObsidianVectorSchema,
  obsidianSemanticConfigFromEnv,
  OBSIDIAN_SEMANTIC_DEFAULT_TOP_K,
  OBSIDIAN_SEMANTIC_DIMENSION,
  OBSIDIAN_SEMANTIC_MAX_TOP_K,
  OBSIDIAN_SEMANTIC_METADATA_TABLE,
  OBSIDIAN_SEMANTIC_MODEL_ID,
  populateObsidianVectors,
  searchObsidianSemantic,
  type ObsidianSemanticConfig,
  type ObsidianSemanticHit,
  type ObsidianSemanticSearchInput,
  type ObsidianSemanticSearchResult,
  type ObsidianVectorPopulationReport,
  type PopulateObsidianVectorsInput,
} from "./semantic-retrieval";

export {
  VAULT_APPROVAL_STATUSES,
  VAULT_CANONICAL_SOURCE_POLICY,
  VAULT_DOMAINS,
  VAULT_GITNEXUS_ARTIFACT_TYPES,
  VAULT_GITNEXUS_NOTE_TYPES,
  VAULT_GITNEXUS_ROUTE_SUBFOLDERS,
  VAULT_LLM_WIKI_NOTE_TYPES,
  VAULT_LLM_WIKI_ROUTE_SUBFOLDERS,
  VAULT_NOTE_STATUSES,
  VAULT_NOTE_TYPES,
  VAULT_PROMOTION_STATUSES,
  VAULT_PROVENANCE_SOURCE_TYPES,
  VAULT_ROOT_FOLDERS,
  VAULT_SENSITIVITY_LEVELS,
  LLM_WIKI_FOLDERS,
  type LlmWikiFolder,
  type VaultGitNexusArtifactType,
  type VaultGitNexusNoteType,
  type VaultLlmWikiNoteType,
  type VaultApprovalStatus,
  type VaultDomain,
  type VaultNoteStatus,
  type VaultNoteType,
  type VaultPromotionStatus,
  type VaultProvenanceSourceType,
  type VaultRootFolder,
  type VaultSensitivity,
} from "./taxonomy";

export {
  GITNEXUS_ARTIFACT_TYPES,
  GITNEXUS_AUTHORITY_CONTRACT,
  GITNEXUS_CONTRACT_VERSION,
  GitNexusArtifactSchema,
  GitNexusArtifactTypeSchema,
  GitNexusRepoIdentitySchema,
  GitNexusRouteDecisionSchema,
  GitNexusSourceContractSchema,
  GitNexusSourceToolSchema,
  createGitNexusLibrarianEnvelope,
  routeGitNexusArtifact,
  type GitNexusArtifact,
  type GitNexusArtifactType,
  type GitNexusRepoIdentity,
  type GitNexusRouteDecision,
  type GitNexusSourceContract,
  type GitNexusSourceTool,
} from "./gitnexus-contract";

export {
  LLM_WIKI_CONTRACT_VERSION,
  LLM_WIKI_GOVERNANCE_CONTRACT,
  LLM_WIKI_LINT_FINDINGS,
  LLM_WIKI_MAINTENANCE_OPERATIONS,
  LLM_WIKI_PAGE_TYPES,
  LLM_WIKI_PAGE_TYPE_TO_NOTE_TYPE,
  LLM_WIKI_PATTERN_SOURCE_URL,
  LLM_WIKI_RAW_SOURCE_TYPES,
  LLM_WIKI_SPECIAL_FILES,
  LlmWikiLintFindingResultSchema,
  LlmWikiLintFindingSchema,
  LlmWikiMaintenanceOperationContractSchema,
  LlmWikiMaintenanceOperationSchema,
  LlmWikiPageDraftSchema,
  LlmWikiPageTypeSchema,
  LlmWikiRawSourceSchema,
  LlmWikiRawSourceTypeSchema,
  createLlmWikiLibrarianEnvelope,
  lintLlmWikiPageDraft,
  planLlmWikiMaintenanceOperation,
  type LlmWikiLintFinding,
  type LlmWikiLintFindingResult,
  type LlmWikiMaintenanceOperation,
  type LlmWikiMaintenanceOperationContract,
  type LlmWikiPageDraft,
  type LlmWikiPageType,
  type LlmWikiRawSource,
  type LlmWikiRawSourceType,
} from "./llm-wiki-contract";

export {
  LLM_WIKI_DRY_RUN_PLANNER_VERSION,
  LLM_WIKI_DRY_RUN_REASONS,
  LLM_WIKI_DRY_RUN_WARNINGS,
  LlmWikiIndexDraftSchema,
  LlmWikiLogDraftSchema,
  LlmWikiMaintenanceDryRunInputSchema,
  LlmWikiMaintenanceDryRunPlanSchema,
  LlmWikiPagePlanSchema,
  planLlmWikiMaintenanceDryRun,
  type LlmWikiDryRunReason,
  type LlmWikiDryRunWarning,
  type LlmWikiGatewayProposalDraft,
  type LlmWikiIndexDraft,
  type LlmWikiLogDraft,
  type LlmWikiMaintenanceDryRunInput,
  type LlmWikiMaintenanceDryRunPlan,
  type LlmWikiPagePlan,
  type LlmWikiPagePreference,
  type LlmWikiSnapshot,
  type LlmWikiSnapshotPage,
} from "./llm-wiki-dry-run-planner";

export {
  KNOWLEDGE_COMPOUNDING_CANDIDATE_TYPES,
  KNOWLEDGE_COMPOUNDING_CONTRACT_VERSION,
  KNOWLEDGE_COMPOUNDING_DETECTION_INPUTS,
  KNOWLEDGE_COMPOUNDING_GOVERNANCE_CONTRACT,
  KNOWLEDGE_COMPOUNDING_PROPOSED_ACTIONS,
  KnowledgeCompoundingCandidateSchema,
  KnowledgeCompoundingCandidateTypeSchema,
  KnowledgeCompoundingDetectionInputSchema,
  KnowledgeCompoundingProposalSchema,
  KnowledgeCompoundingProposedActionSchema,
  createKnowledgeCompoundingLibrarianEnvelope,
  createKnowledgeCompoundingProposal,
  detectKnowledgeCompoundingCandidates,
  type KnowledgeCompoundingCandidate,
  type KnowledgeCompoundingCandidateType,
  type KnowledgeCompoundingDetectionInput,
  type KnowledgeCompoundingProposal,
  type KnowledgeCompoundingProposedAction,
} from "./knowledge-compounding-contract";

export {
  KNOWLEDGE_COMPOUNDING_DETECTOR_REASONS,
  KNOWLEDGE_COMPOUNDING_DETECTOR_VERSION,
  KNOWLEDGE_COMPOUNDING_DETECTOR_WARNINGS,
  KnowledgeCompoundingDetectionResultSchema,
  KnowledgeCompoundingDetectorInputSchema,
  KnowledgeCompoundingEvidenceSchema,
  detectKnowledgeCompoundingCandidatesFromSnapshots,
  type KnowledgeCompoundingDetectionResult,
  type KnowledgeCompoundingDetectorInput,
  type KnowledgeCompoundingDetectorReason,
  type KnowledgeCompoundingDetectorWarning,
  type KnowledgeCompoundingEvidence,
  type KnowledgeCompoundingLibrarianMetadataSnapshot,
  type KnowledgeCompoundingSourceMetadataSnapshot,
  type KnowledgeCompoundingWikiPageSnapshot,
} from "./knowledge-compounding-detector";

export {
  COMPOUNDING_TO_WIKI_ACTION_MAP,
  COMPOUNDING_WIKI_BRIDGE_REASONS,
  COMPOUNDING_WIKI_BRIDGE_VERSION,
  COMPOUNDING_WIKI_BRIDGE_WARNINGS,
  CompoundingWikiBridgeInputSchema,
  CompoundingWikiBridgePlanSchema,
  CompoundingWikiBridgeRecommendationSchema,
  planKnowledgeCompoundingWikiBridge,
  type CompoundingWikiAction,
  type CompoundingWikiBridgeInput,
  type CompoundingWikiBridgePlan,
  type CompoundingWikiBridgeReason,
  type CompoundingWikiBridgeRecommendation,
  type CompoundingWikiBridgeWarning,
} from "./compounding-wiki-bridge";

export {
  KNOWLEDGE_DETECT_CLI_VERSION,
  planKnowledgeDetectionFromIndex,
  printKnowledgeDetectReport,
  runKnowledgeDetectCli,
  type KnowledgeDetectBridgeRecommendationReport,
  type KnowledgeDetectCandidateReport,
  type KnowledgeDetectCliDependencies,
  type KnowledgeDetectCliReport,
} from "./knowledge-detect-cli";

export {
  LLM_WIKI_GENERATION_PLANNER_REASONS,
  LLM_WIKI_GENERATION_PLANNER_VERSION,
  LLM_WIKI_GENERATION_PLANNER_WARNINGS,
  LLM_WIKI_GENERATION_SCOPES,
  LlmWikiGenerationGatewayCompatibilitySchema,
  LlmWikiGenerationPlanSchema,
  LlmWikiGenerationPlannerInputSchema,
  LlmWikiGenerationScopeSchema,
  LlmWikiGenerationSourceCoverageSchema,
  LlmWikiPageDraftPlanSchema,
  planLlmWikiGeneration,
  type LlmWikiGenerationGatewayCompatibility,
  type LlmWikiGenerationPlan,
  type LlmWikiGenerationPlannerInput,
  type LlmWikiGenerationPlannerReason,
  type LlmWikiGenerationPlannerWarning,
  type LlmWikiGenerationScope,
  type LlmWikiGenerationSourceCoverage,
  type LlmWikiPageDraftPlan,
} from "./llm-wiki-generation-planner";

export {
  LLM_WIKI_DRAFT_GENERATOR_REASONS,
  LLM_WIKI_DRAFT_GENERATOR_VERSION,
  LLM_WIKI_DRAFT_GENERATOR_WARNINGS,
  LLM_WIKI_DRAFT_MODEL_ID,
  LlmWikiDraftGeneratorInputSchema,
  LlmWikiDraftGeneratorRuntimeOptionsSchema,
  LlmWikiDraftResultSchema,
  LlmWikiDraftSourceAttributionSchema,
  generateLlmWikiDraft,
  type GenerateLlmWikiDraftDependencies,
  type LlmWikiDraftGeneratorInput,
  type LlmWikiDraftGeneratorReason,
  type LlmWikiDraftGeneratorRuntimeOptions,
  type LlmWikiDraftGeneratorWarning,
  type LlmWikiDraftResult,
  type LlmWikiDraftSourceAttribution,
} from "./llm-wiki-draft-generator";

export {
  LLM_WIKI_DRAFT_CLI_VERSION,
  LLM_WIKI_DRAFT_RUNTIME_DIAGNOSTIC_REASONS,
  createConfiguredLlmWikiDraftRuntime,
  createLlmWikiDraftPreviewFromIndex,
  printLlmWikiDraftCliReport,
  runLlmWikiDraftCli,
  type ConfiguredLlmWikiDraftRuntime,
  type CreateConfiguredLlmWikiDraftRuntimeDependencies,
  type LlmWikiDraftCliDependencies,
  type LlmWikiDraftCliReport,
  type LlmWikiDraftRuntimeDiagnostic,
  type LlmWikiDraftRuntimeDiagnosticReason,
} from "./llm-wiki-draft-cli";

export {
  VAULT_FRONTMATTER_SCHEMA_VERSION,
  VaultAgentAttributionSchema,
  VaultApprovalStatusSchema,
  VaultDomainSchema,
  VaultFrontmatterSchema,
  VaultLifecycleSchema,
  VaultLinksSchema,
  VaultNoteStatusSchema,
  VaultNoteTypeSchema,
  VaultPromotionStatusSchema,
  VaultProvenanceSchema,
  VaultProvenanceSourceTypeSchema,
  VaultSensitivitySchema,
  parseVaultFrontmatter,
  validateVaultFrontmatter,
  type VaultFrontmatter,
} from "./frontmatter";

export {
  isVaultDurableWriteAllowed,
  routeVaultNote,
  slugPathSegment,
  type VaultRouteDecision,
  type VaultRouteKind,
  type VaultRouteStatus,
  type VaultRoutingGovernanceReason,
} from "./routing";

export {
  VAULT_WRITE_GATEWAY_CONTRACT_VERSION,
  VAULT_WRITE_PROPOSAL_REASONS,
  VAULT_WRITE_PROPOSAL_STATES,
  VAULT_WRITE_PROPOSAL_WARNINGS,
  VaultWriteApprovalGateSchema,
  VaultWriteDryRunPlanSchema,
  VaultWriteProposalReasonSchema,
  VaultWriteProposalSchema,
  VaultWriteProposalStateSchema,
  VaultWriteProposalWarningSchema,
  VaultWriteProposingAgentSchema,
  VaultWriteRedactionSummarySchema,
  planVaultWriteProposalDryRun,
  type VaultWriteDryRunPlan,
  type VaultWriteProposal,
  type VaultWriteProposalReason,
  type VaultWriteProposalState,
  type VaultWriteProposalWarning,
} from "./write-gateway";

export {
  LIBRARIAN_CLASSIFICATIONS,
  LIBRARIAN_CLASSIFICATION_TRANSITIONS,
  LIBRARIAN_CONTRACT_VERSION,
  LIBRARIAN_DEDUPLICATION_CONTRACT,
  LIBRARIAN_DECISION_REASONS,
  LIBRARIAN_FRONTMATTER_SCHEMA_VERSION,
  LIBRARIAN_ROUTE_TARGETS,
  LIBRARIAN_SOURCE_TYPES,
  LIBRARIAN_SUPPORTED_NOTE_TYPES,
  LibrarianClassificationSchema,
  LibrarianDecisionReasonSchema,
  LibrarianDeduplicationPlanSchema,
  LibrarianGovernanceSummarySchema,
  LibrarianIngestionDecisionSchema,
  LibrarianIngestionEnvelopeSchema,
  LibrarianPromotionDecisionSchema,
  LibrarianRouteTargetSchema,
  LibrarianSourceIdentifierSchema,
  LibrarianSourceTypeSchema,
  planLibrarianIngestion,
  type LibrarianClassification,
  type LibrarianDecisionReason,
  type LibrarianIngestionDecision,
  type LibrarianIngestionEnvelope,
  type LibrarianRouteTarget,
  type LibrarianSourceIdentifier,
  type LibrarianSourceType,
} from "./librarian-contract";

export {
  LIBRARIAN_DEDUPE_STATUSES,
  LIBRARIAN_DRY_RUN_PLANNER_VERSION,
  LIBRARIAN_DRY_RUN_REASONS,
  LIBRARIAN_DRY_RUN_WARNINGS,
  LIBRARIAN_PROMOTION_RECOMMENDATIONS,
  LibrarianDedupeResultSchema,
  LibrarianDryRunPlanSchema,
  LibrarianDryRunPlannerInputSchema,
  LibrarianPromotionRecommendationSchema,
  planLibrarianIngestionDryRun,
  type LibrarianDedupeStatus,
  type LibrarianDryRunPlan,
  type LibrarianDryRunPlannerInput,
  type LibrarianDryRunReason,
  type LibrarianDryRunRoutePreference,
  type LibrarianDryRunWarning,
  type LibrarianExistingMetadataEntry,
  type LibrarianPromotionRecommendation,
} from "./librarian-dry-run-planner";

export {
  VAULT_WRITE_EXECUTION_CONTRACT_VERSION,
  VAULT_WRITE_EXECUTION_STATUSES,
  VaultWriteExecutionMetadataSchema,
  VaultWriteExecutionStatusSchema,
  executeApprovedVaultWriteProposal,
  renderVaultMarkdown,
  type ExecuteApprovedVaultWriteProposalOptions,
  type VaultWriteExecutionMetadata,
  type VaultWriteExecutionStatus,
} from "./write-execution";
