export {
  buildObsidianVaultIndex,
  getObsidianNoteMetadata,
  getObsidianNoteSnippet,
  loadObsidianVaultConfig,
  OBSIDIAN_INDEX_MAX_NOTE_BYTES,
  OBSIDIAN_SNIPPET_DEFAULT_CHARS,
  OBSIDIAN_SNIPPET_MAX_CHARS,
  OBSIDIAN_VAULT_PATH_ENV,
  ObsidianVaultPathError,
  validateObsidianVaultPath,
  type BuildObsidianVaultIndexOptions,
  type ObsidianFolderMetadata,
  type ObsidianLookupInput,
  type ObsidianNoteMetadata,
  type ObsidianSnippet,
  type ObsidianSnippetInput,
  type ObsidianVaultConfig,
  type ObsidianVaultIndex,
  type ObsidianVaultPathErrorReason,
} from "./pull-indexer";

export {
  countObsidianVectors,
  createObsidianLocalEmbeddingProvider,
  initializeObsidianVectorSchema,
  obsidianSemanticConfigFromEnv,
  OBSIDIAN_SEMANTIC_DEFAULT_TOP_K,
  OBSIDIAN_SEMANTIC_DIMENSION,
  OBSIDIAN_SEMANTIC_MAX_TOP_K,
  OBSIDIAN_SEMANTIC_METADATA_TABLE,
  OBSIDIAN_SEMANTIC_MODEL_ID,
  populateObsidianVectors,
  searchObsidianSemantic,
  type ObsidianSemanticConfig,
  type ObsidianSemanticHit,
  type ObsidianSemanticSearchInput,
  type ObsidianSemanticSearchResult,
  type ObsidianVectorPopulationReport,
  type PopulateObsidianVectorsInput,
} from "./semantic-retrieval";

export {
  VAULT_APPROVAL_STATUSES,
  VAULT_CANONICAL_SOURCE_POLICY,
  VAULT_DOMAINS,
  VAULT_NOTE_STATUSES,
  VAULT_NOTE_TYPES,
  VAULT_PROMOTION_STATUSES,
  VAULT_PROVENANCE_SOURCE_TYPES,
  VAULT_ROOT_FOLDERS,
  VAULT_SENSITIVITY_LEVELS,
  LLM_WIKI_FOLDERS,
  type LlmWikiFolder,
  type VaultApprovalStatus,
  type VaultDomain,
  type VaultNoteStatus,
  type VaultNoteType,
  type VaultPromotionStatus,
  type VaultProvenanceSourceType,
  type VaultRootFolder,
  type VaultSensitivity,
} from "./taxonomy";

export {
  VAULT_FRONTMATTER_SCHEMA_VERSION,
  VaultAgentAttributionSchema,
  VaultApprovalStatusSchema,
  VaultDomainSchema,
  VaultFrontmatterSchema,
  VaultLifecycleSchema,
  VaultLinksSchema,
  VaultNoteStatusSchema,
  VaultNoteTypeSchema,
  VaultPromotionStatusSchema,
  VaultProvenanceSchema,
  VaultProvenanceSourceTypeSchema,
  VaultSensitivitySchema,
  parseVaultFrontmatter,
  validateVaultFrontmatter,
  type VaultFrontmatter,
} from "./frontmatter";

export {
  isVaultDurableWriteAllowed,
  routeVaultNote,
  slugPathSegment,
  type VaultRouteDecision,
  type VaultRouteKind,
  type VaultRouteStatus,
  type VaultRoutingGovernanceReason,
} from "./routing";

export {
  VAULT_WRITE_GATEWAY_CONTRACT_VERSION,
  VAULT_WRITE_PROPOSAL_REASONS,
  VAULT_WRITE_PROPOSAL_STATES,
  VAULT_WRITE_PROPOSAL_WARNINGS,
  VaultWriteApprovalGateSchema,
  VaultWriteDryRunPlanSchema,
  VaultWriteProposalReasonSchema,
  VaultWriteProposalSchema,
  VaultWriteProposalStateSchema,
  VaultWriteProposalWarningSchema,
  VaultWriteProposingAgentSchema,
  VaultWriteRedactionSummarySchema,
  planVaultWriteProposalDryRun,
  type VaultWriteDryRunPlan,
  type VaultWriteProposal,
  type VaultWriteProposalReason,
  type VaultWriteProposalState,
  type VaultWriteProposalWarning,
} from "./write-gateway";

export {
  VAULT_WRITE_EXECUTION_CONTRACT_VERSION,
  VAULT_WRITE_EXECUTION_STATUSES,
  VaultWriteExecutionMetadataSchema,
  VaultWriteExecutionStatusSchema,
  executeApprovedVaultWriteProposal,
  renderVaultMarkdown,
  type ExecuteApprovedVaultWriteProposalOptions,
  type VaultWriteExecutionMetadata,
  type VaultWriteExecutionStatus,
} from "./write-execution";
