export {
  VISION_AUDIT_CATEGORIES,
  VISION_AUDIT_MODULES,
  VISION_AUDIT_TELEMETRY_EVENT_TYPES,
  VISION_AUDIT_VIOLATION_CODES,
  VISION_AUDIT_WARNING_CODES,
  VisionAuditCategorySchema,
  VisionAuditDisabledFeatureStatusSchema,
  VisionAuditGateReplayStepSchema,
  VisionAuditGateResultSchema,
  VisionAuditGateTelemetryEventSchema,
  VisionAuditModuleCoverageSchema,
  VisionAuditModuleSchema,
  VisionAuditTelemetryEventTypeSchema,
  VisionAuditViolationCodeSchema,
  VisionAuditWarningCodeSchema,
  VisionDeveloperObservabilitySummarySchema,
  createVisionAuditGateReplayStep,
  createVisionAuditGateTelemetryEvent,
  evaluateVisionAuditGate,
} from "./audit-gate";

export {
  VISION_MANIFEST_ALLOWED_REPLAY_EDGE_CLASSES,
  VISION_MANIFEST_ALLOWED_REPLAY_NODE_CLASSES,
  VISION_MANIFEST_ALLOWED_TELEMETRY_FIELDS,
  VISION_MANIFEST_DISABLED_FEATURES,
  VISION_MANIFEST_FORBIDDEN_PAYLOAD_CLASSES,
  VISION_MANIFEST_PHASES,
  VISION_MANIFEST_TELEMETRY_EVENT_TYPES,
  VISION_MANIFEST_VIOLATION_CODES,
  VisionDeveloperObservabilityManifestSchema,
  VisionDisabledFeatureManifestSchema,
  VisionManifestAllowedReplayEdgeClassSchema,
  VisionManifestAllowedReplayNodeClassSchema,
  VisionManifestAllowedTelemetryFieldSchema,
  VisionManifestDisabledFeatureSchema,
  VisionManifestForbiddenPayloadClassSchema,
  VisionManifestPhaseSchema,
  VisionManifestReplayStepSchema,
  VisionManifestTelemetryEventSchema,
  VisionManifestTelemetryEventTypeSchema,
  VisionManifestViolationCodeSchema,
  VisionPrivacyTelemetryManifestSchema,
  VisionPrivacyTelemetryManifestValidationSchema,
  VisionRedactionPolicyManifestSchema,
  VisionReplayGraphManifestSchema,
  createDefaultVisionPrivacyTelemetryManifest,
  createVisionManifestReplayStep,
  createVisionManifestTelemetryEvent,
  validateVisionPrivacyTelemetryManifest,
} from "./privacy-telemetry-manifest";

export {
  DEFAULT_VISION_RUNTIME_BOUNDARY_FEATURE_FLAGS,
  VISION_RUNTIME_ALLOWED_OPERATION_CLASSES,
  VISION_RUNTIME_BLOCKED_AUTHORITY_CLASSES,
  VISION_RUNTIME_BOUNDARY_DECISIONS,
  VISION_RUNTIME_BOUNDARY_DISABLED_FEATURES,
  VISION_RUNTIME_BOUNDARY_REASONS,
  VISION_RUNTIME_BOUNDARY_TELEMETRY_EVENT_TYPES,
  VisionRuntimeAllowedOperationClassSchema,
  VisionRuntimeBlockedAuthorityClassSchema,
  VisionRuntimeBoundaryDecisionRecordSchema,
  VisionRuntimeBoundaryDecisionSchema,
  VisionRuntimeBoundaryDisabledFeatureSchema,
  VisionRuntimeBoundaryFeatureFlagsSchema,
  VisionRuntimeBoundaryReasonSchema,
  VisionRuntimeBoundaryReplayStepSchema,
  VisionRuntimeBoundaryTelemetryEventSchema,
  VisionRuntimeBoundaryTelemetryEventTypeSchema,
  VisionRuntimeOperationClassSchema,
  assertVisionRuntimeBoundary,
  createVisionRuntimeBoundaryReplayStep,
  createVisionRuntimeBoundaryTelemetryEvent,
  evaluateVisionRuntimeBoundary,
} from "./runtime-boundary-guard";

export {
  DEFAULT_VISION_FALLBACK_FEATURE_FLAGS,
  DEFAULT_VISION_FALLBACK_POLICY,
  VISION_FALLBACK_BUDGET_STATES,
  VISION_FALLBACK_CONSENT_STATES,
  VISION_FALLBACK_DECISIONS,
  VISION_FALLBACK_DISABLED_FEATURES,
  VISION_FALLBACK_REASONS,
  VISION_FALLBACK_TELEMETRY_EVENT_TYPES,
  VisionFallbackBudgetStateSchema,
  VisionFallbackConsentStateSchema,
  VisionFallbackDecisionRecordSchema,
  VisionFallbackDecisionSchema,
  VisionFallbackDisabledFeatureSchema,
  VisionFallbackFeatureFlagsSchema,
  VisionFallbackPolicySchema,
  VisionFallbackReasonSchema,
  VisionFallbackReplayStepSchema,
  VisionFallbackTelemetryEventSchema,
  VisionFallbackTelemetryEventTypeSchema,
  createVisionFallbackReplayStep,
  createVisionFallbackTelemetryEvent,
  evaluateVisionFallback,
} from "./fallback-governance";

export {
  DEFAULT_VISION_CONTEXT_CAPS,
  DEFAULT_VISION_CONTEXT_FEATURE_FLAGS,
  VISION_CONTEXT_DISABLED_FEATURES,
  VISION_CONTEXT_TELEMETRY_EVENT_TYPES,
  VisionContextCapsSchema,
  VisionContextClassSummarySchema,
  VisionContextDisabledFeatureSchema,
  VisionContextFeatureFlagsSchema,
  VisionContextProvenanceSchema,
  VisionContextReplayStepSchema,
  VisionContextSnapshotSchema,
  VisionContextTelemetryEventSchema,
  VisionContextTelemetryEventTypeSchema,
  assembleVisionContext,
  createVisionContextReplayStep,
  createVisionContextTelemetryEvent,
} from "./context-assembly";

export {
  DEFAULT_VISION_OBSERVATION_FEATURE_FLAGS,
  VISION_OBSERVATION_CLASSES,
  VISION_OBSERVATION_DISABLED_FEATURES,
  VisionObservationAggregateSchema,
  VisionObservationClassSchema,
  VisionObservationDisabledFeatureSchema,
  VisionObservationFeatureFlagsSchema,
  VisionObservationReplayStepSchema,
  VisionObservationSchema,
  aggregateVisionObservations,
  createVisionObservation,
  createVisionObservationReplayStep,
} from "./observation";

export {
  DEFAULT_VISION_PROVIDER_FEATURE_FLAGS,
  VISION_LOCAL_PROVIDER_CONTRACTS,
  VISION_LOCAL_PROVIDER_IDS,
  VISION_PROVIDER_CAPABILITIES,
  VISION_PROVIDER_DISABLED_FEATURES,
  VISION_PROVIDER_ELIGIBILITY_REASONS,
  VISION_PROVIDER_ELIGIBILITY_STATUSES,
  VISION_PROVIDER_RESULT_CLASSES,
  VISION_PROVIDER_TELEMETRY_EVENT_TYPES,
  VisionLocalProviderContractSchema,
  VisionLocalProviderIdSchema,
  VisionProviderCapabilitySchema,
  VisionProviderDisabledFeatureSchema,
  VisionProviderEligibilityDecisionSchema,
  VisionProviderEligibilityReasonSchema,
  VisionProviderEligibilityStatusSchema,
  VisionProviderFeatureFlagsSchema,
  VisionProviderReplayStepSchema,
  VisionProviderResultClassSchema,
  VisionProviderResultSchema,
  VisionProviderTelemetryEventSchema,
  VisionProviderTelemetryEventTypeSchema,
  confidenceBandForScore,
  createVisionProviderReplayStep,
  createVisionProviderResult,
  createVisionProviderTelemetryEvent,
  findEligibleVisionProviders,
} from "./local-provider-contract";

export {
  DEFAULT_VISION_FRAME_FEATURE_FLAGS,
  VISION_FRAME_DISABLED_FEATURES,
  VISION_FRAME_INGESTION_REASONS,
  VISION_FRAME_INGESTION_STATUSES,
  VISION_FRAME_SOURCE_TYPES,
  VISION_FRAME_TELEMETRY_EVENT_TYPES,
  VisionFrameDescriptorSchema,
  VisionFrameDisabledFeatureSchema,
  VisionFrameFeatureFlagsSchema,
  VisionFrameIngestionReasonSchema,
  VisionFrameIngestionResultSchema,
  VisionFrameIngestionStatusSchema,
  VisionFrameSourceTypeSchema,
  VisionFrameTelemetryEventSchema,
  VisionFrameTelemetryEventTypeSchema,
  createVisionFrameDescriptor,
  createVisionFrameTelemetryEvent,
  ingestVisionFrameDescriptor,
  validateVisionFrameDescriptor,
} from "./frame-ingestion";

export {
  DEFAULT_VISION_SESSION_FEATURE_FLAGS,
  VISION_SESSION_DISABLED_FEATURES,
  VISION_SESSION_EVENT_TYPES,
  VISION_SESSION_REASONS,
  VISION_SESSION_STATES,
  VISION_SESSION_SURFACES,
  VisionFailureReplayReferenceSchema,
  VisionSessionDisabledFeatureSchema,
  VisionSessionEventTypeSchema,
  VisionSessionFeatureFlagsSchema,
  VisionSessionReasonSchema,
  VisionSessionRecordSchema,
  VisionSessionStateSchema,
  VisionSessionSurfaceSchema,
  VisionSessionTelemetryEventSchema,
  cancelVisionSession,
  completeVisionSession,
  createVisionSessionTelemetryEvent,
  expireVisionSession,
  failVisionSession,
  requestVisionSession,
  startVisionSession,
} from "./session";

export {
  DEFAULT_VISION_FAILURE_REPLAY_FEATURE_FLAGS,
  VISION_REPLAY_APPROVAL_DECISIONS,
  VISION_REPLAY_CONFIDENCE_BANDS,
  VISION_REPLAY_DISABLED_FEATURES,
  VISION_REPLAY_FALLBACK_DECISIONS,
  VISION_REPLAY_FALLBACK_REASONS,
  VISION_REPLAY_INPUT_TYPES,
  VISION_REPLAY_LOCAL_PROVIDERS,
  VISION_REPLAY_REDACTION_STATUSES,
  VISION_REPLAY_RESULT_CLASSES,
  VisionFailureReplayFeatureFlagsSchema,
  VisionFailureReplayGraphEdgeSchema,
  VisionFailureReplayGraphNodeSchema,
  VisionFailureReplayGraphSchema,
  VisionFailureReplayRecordSchema,
  VisionReplayApprovalDecisionSchema,
  VisionReplayConfidenceBandSchema,
  VisionReplayDisabledFeatureSchema,
  VisionReplayFallbackDecisionSchema,
  VisionReplayFallbackReasonSchema,
  VisionReplayInputTypeSchema,
  VisionReplayLocalProviderSchema,
  VisionReplayRedactionStatusSchema,
  VisionReplayResultClassSchema,
  buildVisionFailureReplayGraph,
  createVisionFailureReplayRecord,
} from "./failure-replay";

export type {
  VisionAuditCategory,
  VisionAuditDisabledFeatureStatus,
  VisionAuditGateReplayStep,
  VisionAuditGateResult,
  VisionAuditGateTelemetryEvent,
  VisionAuditModule,
  VisionAuditModuleCoverage,
  VisionAuditTelemetryEventType,
  VisionAuditViolationCode,
  VisionAuditWarningCode,
  VisionDeveloperObservabilitySummary,
} from "./audit-gate";

export type {
  VisionDeveloperObservabilityManifest,
  VisionDisabledFeatureManifest,
  VisionManifestAllowedReplayEdgeClass,
  VisionManifestAllowedReplayNodeClass,
  VisionManifestAllowedTelemetryField,
  VisionManifestDisabledFeature,
  VisionManifestForbiddenPayloadClass,
  VisionManifestPhase,
  VisionManifestReplayStep,
  VisionManifestTelemetryEvent,
  VisionManifestTelemetryEventType,
  VisionManifestViolationCode,
  VisionPrivacyTelemetryManifest,
  VisionPrivacyTelemetryManifestValidation,
  VisionRedactionPolicyManifest,
  VisionReplayGraphManifest,
} from "./privacy-telemetry-manifest";

export type {
  VisionRuntimeAllowedOperationClass,
  VisionRuntimeBlockedAuthorityClass,
  VisionRuntimeBoundaryDecision,
  VisionRuntimeBoundaryDecisionRecord,
  VisionRuntimeBoundaryDisabledFeature,
  VisionRuntimeBoundaryFeatureFlags,
  VisionRuntimeBoundaryReason,
  VisionRuntimeBoundaryReplayStep,
  VisionRuntimeBoundaryTelemetryEvent,
  VisionRuntimeBoundaryTelemetryEventType,
  VisionRuntimeOperationClass,
} from "./runtime-boundary-guard";

export type {
  VisionFallbackBudgetState,
  VisionFallbackConsentState,
  VisionFallbackDecision,
  VisionFallbackDecisionRecord,
  VisionFallbackDisabledFeature,
  VisionFallbackFeatureFlags,
  VisionFallbackPolicy,
  VisionFallbackReason,
  VisionFallbackReplayStep,
  VisionFallbackTelemetryEvent,
  VisionFallbackTelemetryEventType,
} from "./fallback-governance";

export type {
  VisionContextCaps,
  VisionContextClassSummary,
  VisionContextDisabledFeature,
  VisionContextFeatureFlags,
  VisionContextProvenance,
  VisionContextReplayStep,
  VisionContextSnapshot,
  VisionContextTelemetryEvent,
  VisionContextTelemetryEventType,
} from "./context-assembly";

export type {
  VisionObservation,
  VisionObservationAggregate,
  VisionObservationClass,
  VisionObservationDisabledFeature,
  VisionObservationFeatureFlags,
  VisionObservationReplayStep,
} from "./observation";

export type {
  VisionLocalProviderContract,
  VisionLocalProviderId,
  VisionProviderCapability,
  VisionProviderDisabledFeature,
  VisionProviderEligibilityDecision,
  VisionProviderEligibilityReason,
  VisionProviderEligibilityStatus,
  VisionProviderFeatureFlags,
  VisionProviderReplayStep,
  VisionProviderResult,
  VisionProviderResultClass,
  VisionProviderTelemetryEvent,
  VisionProviderTelemetryEventType,
} from "./local-provider-contract";

export type {
  VisionFrameDescriptor,
  VisionFrameDisabledFeature,
  VisionFrameFeatureFlags,
  VisionFrameIngestionReason,
  VisionFrameIngestionResult,
  VisionFrameIngestionStatus,
  VisionFrameSourceType,
  VisionFrameTelemetryEvent,
  VisionFrameTelemetryEventType,
} from "./frame-ingestion";

export type {
  VisionFailureReplayReference,
  VisionSessionDisabledFeature,
  VisionSessionEventType,
  VisionSessionFeatureFlags,
  VisionSessionReason,
  VisionSessionRecord,
  VisionSessionState,
  VisionSessionSurface,
  VisionSessionTelemetryEvent,
} from "./session";

export type {
  VisionFailureReplayFeatureFlags,
  VisionFailureReplayGraph,
  VisionFailureReplayGraphEdge,
  VisionFailureReplayGraphNode,
  VisionFailureReplayRecord,
  VisionReplayApprovalDecision,
  VisionReplayConfidenceBand,
  VisionReplayDisabledFeature,
  VisionReplayFallbackDecision,
  VisionReplayFallbackReason,
  VisionReplayInputType,
  VisionReplayLocalProvider,
  VisionReplayRedactionStatus,
  VisionReplayResultClass,
} from "./failure-replay";
