export type TelemetryEventType =
  | "validation_failure"
  | "rate_limited"
  | "cost_denied"
  | "safety_blocked"
  | "confirmation_required"
  | "model_call"
  | "provider_error"
  | "client_disconnect"
  | "tool_proposed"
  | "tool_executed"
  | "tool_completed"
  | "tool_timeout"
  | "tool_cancelled"
  | "tool_denied"
  | "tool_approved"
  | "tool_rolled_back"
  | "memory_write"
  | "memory_read"
  | "memory_embedding_created"
  | "memory_vector_search"
  | "memory_surfaced"
  | "memory_forget"
  | "memory_distill_rejected"
  | "session_summary_saved"
  | "session_summary_generated"
  | "session_summary_triggered"
  | "session_summary_skipped"
  | "session_summary_failed"
  | "working_memory_assembled"
  | "context_budget_breach"
  | "project_state_saved"
  | "project_state_read"
  | "project_context_detected"
  | "memory_candidate_generated"
  | "memory_candidate_reviewed"
  | "memory_candidate_rejected"
  | "consent_read"
  | "consent_granted"
  | "consent_revoked"
  | "consent_denied"
  | "preference_saved"
  | "preference_read"
  | "preference_superseded"
  | "goal_created"
  | "goal_read"
  | "goal_status_changed"
  | "goal_touched"
  | "timeline_read"
  | "timeline_projected"
  | "memory_weighting_read"
  | "memory_weighting_projected"
  | "curator_action"
  | "curator_merge"
  | "curator_split"
  | "curator_archive"
  | "curator_delete"
  | "review_queue_read"
  | "review_item_updated"
  | "review_item_dismissed"
  | "reflection_prompt_requested"
  | "reflection_prompt_generated"
  | "reflection_prompt_blocked"
  | "keeper_registry_read"
  | "keeper_registration_blocked"
  | "keeper_registered"
  | "personal_context_access_granted"
  | "personal_context_access_denied"
  | "consent_revocation_processed"
  | "consent_revocation_cache_invalidated"
  | "consent_revocation_blocked_projection"
  | "runtime_write_denied"
  | "runtime_write_allowed"
  | "runtime_write_boundary_violation"
  | "runtime_command_registered"
  | "runtime_command_registry_read"
  | "runtime_command_validation_failed"
  | "runtime_command_call_created"
  | "runtime_command_call_updated"
  | "runtime_command_output_ref_attached"
  | "runtime_command_proposed"
  | "runtime_command_approved"
  | "runtime_command_denied"
  | "runtime_command_approval_expired";

export interface TelemetryEvent {
  timestamp: number;
  event_type: TelemetryEventType;
  success: boolean;
  session_id?: string;
  intent?: string;
  safety_tag?: string;
  tier?: string;
  model_id?: string;
  tool_name?: string;
  execution_id?: string;
  input_tokens?: number;
  output_tokens?: number;
  latency_ms?: number;
  time_to_first_token_ms?: number;
  cost_usd?: number;
  error_class?: string;
  user_rating?: number;
  notes?: string;
}

export interface TelemetryStore {
  record(event: TelemetryEvent): void;
  list(limit?: number): TelemetryEvent[];
  reset(): void;
}
